name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true        # Cancel any in-flight run when a new commit arrives :contentReference[oaicite:0]{index=0}

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.13' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}  # Always pin the version explicitly :contentReference[oaicite:1]{index=1}
          cache: 'pip'                                  # Auto-cache your pip deps between runs :contentReference[oaicite:2]{index=2}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Lint code
        run: |
          pip install flake8
          flake8 src

      - name: Run tests
        run: pytest
